name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: >
            sudo apt update &&
            sudo apt install meson

      - name: Build
        run: meson build && ninja -C build
